## Get Clinical Data from the the first medical examination corresponding to the patients of which MRI Images are available

### Carlos Sanmiguel Vila

In [ ]:
# Packages

import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [ ]:
# ADNI MERGE

filename_1 =  '/content/drive/My Drive/ADNI/Dataset/TabularData/ADNIMERGE_COL.csv' # Demographic data and Cognitive tests
filename_2 =  '/content/drive/My Drive/ADNI/Dataset/TabularData/DESIKANLAB.csv' # Genetic Data
file_label = '/content/drive/My Drive/ADNI/N3D2.npy' # id patients with MRI

### Labels

In [ ]:
# Label Data
label = ['RID','PTID']
state = ['VISCODE','DX_bl']

### Demographic data
**AGE**: Age in years, **PTGENDER**: Gender (Male/Female), **PTETHCAT**: Years of education, **PTETHCAT**: Ethnic, (Not Hisp/Latino, Hisp/Latino, Unknown), **PTRACCAT**: Race, ('White', 'More than one', 'Am Indian/Alaskan', 'Asian'), **PTMARRY**: Marital Status ('Married', 'Widowed', 'Divorced', 'Never married', 'Unknown')

In [ ]:
# Demographic Data
dem_data = ['AGE','PTGENDER','PTEDUCAT','PTETHCAT','PTRACCAT','PTMARRY']

### Cognitive tests
**APOE4 expression level**: gene APOE4, **CDRSB**: Clinical Dementia Rating Scaleâ€“Sum of Boxes, **ADAS11**: Alzheimer's Disease Assessment Scale-Cognitive Subscale based on 11 questions, **ADAS13**: Alzheimer's Disease Assessment Scale-Cognitive Subscale based on 13 questions, **MMSE**: Mini-Mental State Examination, **RAVLT_immediate, RAVLT_learning, RAVLT_perc_forgetting**: Rey's Auditory Verbal Learning Test, **FAQ**: Functional Activities Questionnaire

In [ ]:
test_data = ['APOE4','CDRSB','ADAS11','ADAS13','MMSE','RAVLT_immediate','RAVLT_learning','RAVLT_perc_forgetting','FAQ']

In [ ]:
variables = label + state + dem_data + test_data
df_aux = pd.read_csv(filename_1, sep=';',usecols=variables)
df_aux.head()

   RID        PTID VISCODE  ... RAVLT_learning  RAVLT_perc_forgetting   FAQ
0    2  011_S_0002      bl  ...            4.0                545.455   0.0
1    3  011_S_0003      bl  ...            1.0                100.000  10.0
2    3  011_S_0003     m06  ...            2.0                100.000  12.0
3    3  011_S_0003     m12  ...            2.0                100.000  17.0
4    3  011_S_0003     m24  ...            1.0                100.000  14.0

[5 rows x 19 columns]

## Genetic Data
**PHS**: polygenic hazard score

In [ ]:
df2_aux = pd.read_csv(filename_2,delimiter=',',usecols=['RID','PHS'])
df2_aux.head()

   RID       PHS
0    2 -0.096111
1    3  0.414711
2    5 -0.373703
3    6 -0.105310
4    8 -1.080340

In [ ]:
df = pd.merge(df_aux,df2_aux,on ='RID',how='outer')
df.head(10)

   RID        PTID VISCODE  ... RAVLT_perc_forgetting  FAQ       PHS
0    2  011_S_0002      bl  ...               545.455  0.0 -0.096111
1    2  011_S_0002     m06  ...                37.500  0.0 -0.096111
2    2  011_S_0002     m36  ...                87.500  0.0 -0.096111
3    2  011_S_0002     m60  ...                40.000  0.0 -0.096111
4    2  011_S_0002     m66  ...                   NaN  NaN -0.096111
5    2  011_S_0002    m126  ...                   NaN  NaN -0.096111
6    2  011_S_0002    m120  ...                80.000  0.0 -0.096111
7    2  011_S_0002    m108  ...                   NaN  0.0 -0.096111
8    2  011_S_0002    m102  ...                   NaN  NaN -0.096111
9    2  011_S_0002     m96  ...               666.667  0.0 -0.096111

[10 rows x 20 columns]

In [ ]:
df.shape

(14699, 20)

In [ ]:
df.dtypes

RID                        int64
PTID                      object
VISCODE                   object
DX_bl                     object
AGE                      float64
PTGENDER                  object
PTEDUCAT                   int64
PTETHCAT                  object
PTRACCAT                  object
PTMARRY                   object
APOE4                    float64
CDRSB                    float64
ADAS11                   float64
ADAS13                   float64
MMSE                     float64
RAVLT_immediate          float64
RAVLT_learning           float64
RAVLT_perc_forgetting    float64
FAQ                      float64
PHS                      float64
dtype: object

In [ ]:
df.isnull().sum()

RID                         0
PTID                        0
VISCODE                     0
DX_bl                      12
AGE                         4
PTGENDER                    0
PTEDUCAT                    0
PTETHCAT                    0
PTRACCAT                    0
PTMARRY                     0
APOE4                     273
CDRSB                    4133
ADAS11                   4271
ADAS13                   4368
MMSE                     4227
RAVLT_immediate          4354
RAVLT_learning           4353
RAVLT_perc_forgetting    4454
FAQ                      4130
PHS                      2352
dtype: int64

In [ ]:
labels = np.load(file_label)

In [ ]:
labels.shape

(694,)

In [ ]:
df['label'] = df['PTID'].str.replace(r'_', '').astype(str)

In [ ]:
df.head(10)

   RID        PTID VISCODE  ...  FAQ       PHS     label
0    2  011_S_0002      bl  ...  0.0 -0.096111  011S0002
1    2  011_S_0002     m06  ...  0.0 -0.096111  011S0002
2    2  011_S_0002     m36  ...  0.0 -0.096111  011S0002
3    2  011_S_0002     m60  ...  0.0 -0.096111  011S0002
4    2  011_S_0002     m66  ...  NaN -0.096111  011S0002
5    2  011_S_0002    m126  ...  NaN -0.096111  011S0002
6    2  011_S_0002    m120  ...  0.0 -0.096111  011S0002
7    2  011_S_0002    m108  ...  0.0 -0.096111  011S0002
8    2  011_S_0002    m102  ...  NaN -0.096111  011S0002
9    2  011_S_0002     m96  ...  0.0 -0.096111  011S0002

[10 rows x 21 columns]

In [ ]:
df_pre = df[df['label'].isin(labels.tolist())]

In [ ]:
sum(df['label']==labels.tolist()[0])

6

In [ ]:
df_pre.shape

(5670, 21)

In [ ]:
df_pre

       RID        PTID VISCODE  ...  FAQ       PHS     label
0        2  011_S_0002      bl  ...  0.0 -0.096111  011S0002
1        2  011_S_0002     m06  ...  0.0 -0.096111  011S0002
2        2  011_S_0002     m36  ...  0.0 -0.096111  011S0002
3        2  011_S_0002     m60  ...  0.0 -0.096111  011S0002
4        2  011_S_0002     m66  ...  NaN -0.096111  011S0002
...    ...         ...     ...  ...  ...       ...       ...
13906  692  094_S_0692     m12  ...  0.0  0.312033  094S0692
13907  692  094_S_0692     m18  ...  NaN  0.312033  094S0692
13908  692  094_S_0692     m24  ...  0.0  0.312033  094S0692
13909  692  094_S_0692     m30  ...  NaN  0.312033  094S0692
13910  876  109_S_0876      bl  ...  0.0       NaN  109S0876

[5670 rows x 21 columns]

In [ ]:
def custom_round(x, base=4):
    return int(base * round(float(x)/base))

nan_vars = df_pre.columns[df_pre[df_pre.VISCODE == 'bl'].isna().any()].tolist()

for nan_var in nan_vars:

  df_aux = df_pre[[nan_var,'AGE','PTGENDER','DX_bl']]
  df_aux = df_aux.dropna(subset = ['AGE'])
  df_aux.loc[:,'AGE'] = df_aux['AGE'].apply(lambda x: custom_round(x, base=5))

  df_aux = df_aux.fillna(df_aux.groupby(['AGE','PTGENDER','PTGENDER','DX_bl']).transform('mean'))
  df_pre[nan_var] = df_aux[nan_var]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [ ]:
df_bl = df_pre[df_pre.VISCODE =='bl']

In [ ]:
df_bl.loc[:,'PHS'] = df_bl['PHS'].fillna(df_bl['PHS'].mean())

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [ ]:
df_bl.isnull().sum()

RID                      0
PTID                     0
VISCODE                  0
DX_bl                    0
AGE                      0
PTGENDER                 0
PTEDUCAT                 0
PTETHCAT                 0
PTRACCAT                 0
PTMARRY                  0
APOE4                    0
CDRSB                    0
ADAS11                   0
ADAS13                   0
MMSE                     0
RAVLT_immediate          0
RAVLT_learning           0
RAVLT_perc_forgetting    0
FAQ                      0
PHS                      0
label                    0
dtype: int64

In [ ]:
df_bl.shape

(694, 21)

In [ ]:
df_bl.head()

    RID        PTID VISCODE  ...   FAQ       PHS     label
0     2  011_S_0002      bl  ...   0.0 -0.096111  011S0002
16    3  011_S_0003      bl  ...  10.0  0.414711  011S0003
21    4  022_S_0004      bl  ...   0.0  0.647089  022S0004
27    5  011_S_0005      bl  ...   0.0 -0.373703  011S0005
34    6  100_S_0006      bl  ...   0.0 -0.105310  100S0006

[5 rows x 21 columns]

In [ ]:
labels

array(['128S1242', '128S0272', '002S1155', '068S0478', '031S0351',
       '098S0269', '012S0720', '094S1267', '011S0861', '116S0382',
       '094S0921', '011S0362', '029S0824', '007S1206', '128S1043',
       '002S0619', '005S0814', '094S1398', '007S1248', '052S0951',
       '068S0401', '022S0924', '126S0405', '027S1045', '041S0679',
       '136S0086', '099S0090', '126S0506', '116S0361', '022S0750',
       '137S0972', '023S1289', '037S0539', '035S0292', '005S0546',
       '029S1056', '006S0681', '033S0889', '141S0853', '100S0995',
       '130S0449', '011S0053', '133S1055', '021S0273', '011S0010',
       '100S0296', '136S0873', '033S0511', '012S0634', '032S0095',
       '029S0871', '023S0388', '035S0341', '041S1260', '018S0286',
       '027S1385', '051S1072', '116S0657', '022S0544', '023S1306',
       '109S0967', '016S1117', '003S0907', '003S1122', '005S0553',
       '032S0479', '141S1004', '033S0741', '136S0429', '109S0950',
       '022S0044', '126S0708', '057S0839', '033S1016', '041S1368',
       '133S0771', '037S1421', '126S0605', '041S1425', '116S1083',
       '027S0408', '128S0608', '141S1094', '029S0878', '035S0156',
       '027S0485', '114S0601', '057S0464', '123S0050', '941S1197',
       '130S0423', '022S1351', '136S0695', '011S0326', '027S1081',
       '032S1101', '067S0336', '016S1149', '073S0312', '136S0107',
       '012S0689', '037S0303', '128S1148', '012S0932', '127S0754',
       '133S0488', '006S0498', '132S0339', '024S1307', '123S0072',
       '011S0168', '130S0969', '073S0518', '022S0543', '067S0243',
       '023S0963', '062S1182', '016S0991', '121S1350', '133S0433',
       '016S1121', '130S0102', '136S0194', '002S0782', '941S1203',
       '023S1190', '013S1205', '123S0091', '116S1315', '029S1073',
       '082S1256', '009S1334', '141S1255', '041S0125', '082S0469',
       '013S0860', '128S0227', '062S0690', '009S0842', '116S1271',
       '099S0372', '130S1290', '036S0813', '067S0029', '023S0217',
       '010S0067', '018S0682', '127S1032', '027S0074', '036S1240',
       '114S1118', '022S0004', '003S1074', '016S1092', '036S0759',
       '141S1231', '033S0723', '127S0684', '029S1384', '033S0906',
       '100S0743', '067S0110', '005S0610', '133S0727', '137S0158',
       '010S0786', '011S0008', '009S1354', '012S0712', '041S0314',
       '082S1079', '011S0183', '082S0640', '136S0300', '062S1294',
       '141S0915', '023S0916', '033S0739', '082S0761', '041S0598',
       '121S1322', '116S0370', '037S0182', '018S0087', '023S0126',
       '009S0862', '109S1114', '023S0376', '023S0139', '006S1130',
       '128S0216', '002S0954', '127S0260', '022S1394', '116S1243',
       '109S1343', '052S0671', '013S0502', '010S0420', '128S0715',
       '123S0113', '036S0672', '010S0419', '128S0947', '033S1309',
       '033S0724', '021S0141', '027S0179', '022S0066', '094S1188',
       '035S0997', '033S1086', '003S1021', '003S1059', '007S0068',
       '023S0604', '016S1263', '129S1204', '137S0686', '131S0319',
       '137S1426', '029S1218', '036S0869', '068S0872', '073S0445',
       '067S0284', '137S0841', '033S1308', '116S0648', '013S0240',
       '123S1300', '018S0142', '013S1161', '100S1113', '073S0386',
       '067S0176', '014S0520', '062S1099', '007S0414', '062S0578',
       '131S0441', '137S0800', '011S0005', '051S1123', '132S0987',
       '023S0331', '014S0563', '129S1246', '013S1035', '109S0777',
       '133S0629', '036S0576', '016S0538', '141S0767', '128S0740',
       '022S0129', '031S0568', '007S0293', '094S0692', '041S1412',
       '094S1293', '057S0818', '094S0531', '141S0726', '136S1227',
       '128S0528', '033S1285', '022S1097', '029S1184', '073S0311',
       '009S0751', '116S0360', '098S0160', '141S0697', '037S0627',
       '128S0611', '036S0577', '036S0748', '033S0920', '041S1391',
       '057S1007', '012S1321', '053S0389', '062S0793', '023S0081',
       '941S1195', '032S0147', '068S0109', '057S1371', '128S0310',
       '041S1420', '100S1154', '023S0061', '023S1247', '136S0195',
       '062S0535', '027S0644', '123S0088', '023S0084', '029S0914',
       '128S0188', '002S0559', '011S0002', '051S1296', '128S0135',
       '006S0675', '027S0417', '094S0434', '021S0626', '067S0290',
       '136S0184', '094S0526', '051S1338', '041S0262', '033S1284',
       '016S0359', '141S1024', '067S0177', '131S0497', '136S0196',
       '012S1292', '041S1411', '126S1221', '099S0534', '067S0607',
       '128S0225', '033S1279', '029S1215', '023S1046', '012S1175',
       '057S1217', '020S0883', '100S0069', '032S0978', '022S0007',
       '033S0567', '131S1301', '127S0393', '128S0229', '020S0097',
       '007S0316', '005S0221', '033S1283', '072S0315', '130S0505',
       '023S0093', '067S1253', '018S0057', '022S0961', '128S0205',
       '016S0769', '073S0089', '010S0472', '011S0021', '099S0352',
       '127S0394', '018S0155', '068S1075', '141S1051', '100S0930',
       '116S1249', '002S1280', '022S0096', '021S0984', '029S0999',
       '036S1023', '073S0909', '005S0448', '094S1164', '094S1090',
       '136S0579', '002S0955', '116S0752', '114S0458', '136S0874',
       '016S1138', '116S0649', '037S0377', '098S0884', '126S1340',
       '141S0810', '032S1037', '027S0118', '127S1140', '012S1212',
       '037S0327', '011S1080', '013S1186', '141S1244', '128S1408',
       '014S0328', '013S1275', '021S0647', '023S0078', '141S1052',
       '137S0366', '136S0299', '067S0812', '036S0945', '027S0850',
       '037S0501', '137S0481', '127S1419', '131S0457', '031S0294',
       '012S0917', '014S0558', '037S0566', '006S0484', '053S0621',
       '109S1157', '133S1170', '082S0304', '051S1131', '114S0410',
       '027S0461', '133S0913', '098S0172', '137S0283', '022S0014',
       '037S1078', '018S0335', '130S1337', '137S0722', '022S1366',
       '052S1168', '128S1406', '003S1057', '099S1034', '099S0040',
       '057S0779', '007S0249', '031S0821', '126S0784', '013S0325',
       '027S0404', '020S1288', '133S0525', '123S0390', '032S0187',
       '082S1119', '057S0957', '029S1038', '128S0863', '109S1183',
       '007S1339', '005S0572', '094S1397', '133S0792', '010S0422',
       '021S0276', '032S0718', '067S0045', '133S0912', '033S1098',
       '127S0431', '941S1311', '007S0041', '133S0638', '010S0161',
       '016S1028', '010S0904', '128S1088', '127S1427', '018S0633',
       '002S0816', '007S0070', '098S0149', '014S0356', '041S1418',
       '141S1152', '053S0919', '128S0770', '073S0565', '128S1407',
       '100S0747', '062S1299', '137S1041', '003S1257', '023S0613',
       '029S0845', '023S0887', '067S0056', '027S0256', '128S0517',
       '127S0397', '003S0908', '141S1245', '002S0413', '062S0768',
       '094S1402', '099S0054', '016S0354', '027S1277', '022S0219',
       '005S0929', '128S0200', '137S1414', '082S0832', '137S0973',
       '082S1377', '027S1213', '032S0214', '094S1330', '041S0407',
       '100S0006', '023S0042', '109S1013', '024S1393', '021S0424',
       '130S0289', '127S0844', '036S0760', '099S0051', '023S0926',
       '123S0108', '018S0103', '020S0213', '002S1018', '007S0128',
       '131S0409', '005S0223', '127S1210', '130S0285', '072S1380',
       '021S1109', '024S1400', '023S1104', '131S0384', '027S0116',
       '023S0058', '002S0295', '109S1014', '037S1225', '116S0834',
       '057S0643', '137S0796', '011S0241', '099S0492', '037S0588',
       '136S0426', '116S0890', '123S0094', '005S0324', '023S0030',
       '021S0343', '116S0487', '068S0442', '041S1423', '941S1295',
       '128S1430', '009S1199', '036S0673', '033S0922', '128S0245',
       '067S0098', '037S0150', '053S1044', '057S1373', '114S0979',
       '068S0802', '099S1144', '005S1224', '027S1254', '033S0733',
       '016S1326', '128S0500', '131S1389', '137S0438', '128S0266',
       '941S1363', '100S0190', '094S1027', '128S1409', '023S0625',
       '128S0545', '018S0369', '057S0474', '023S0855', '067S0076',
       '126S1187', '082S0928', '027S0403', '031S0554', '031S1209',
       '057S1269', '018S0043', '041S0446', '067S0077', '128S0167',
       '082S0363', '033S0514', '099S0470', '141S0696', '073S1357',
       '057S1379', '023S1262', '027S1082', '006S0547', '130S1201',
       '068S1191', '033S1281', '141S0790', '067S1185', '114S1103',
       '068S0476', '007S0698', '057S0941', '130S0956', '100S1286',
       '067S0828', '013S1120', '041S0282', '013S0996', '021S0231',
       '067S0059', '005S1341', '027S0307', '012S0803', '021S0753',
       '005S0222', '126S0606', '014S0169', '006S0653', '012S1033',
       '041S0549', '002S0938', '021S0642', '099S0551', '133S1031',
       '116S0392', '099S0291', '018S0450', '013S0592', '011S0003',
       '011S0016', '100S0892', '137S0668', '002S0729', '141S0851',
       '007S0344', '027S1387', '051S1331', '018S0406', '041S1435',
       '031S1066', '127S0112', '023S0083', '031S0867', '073S0746',
       '052S1251', '032S0400', '126S1077', '012S1165', '141S1137',
       '029S0836', '128S0138', '018S0080', '094S1417', '098S0667',
       '082S0641', '136S0186', '141S1378', '100S1062', '022S0130',
       '016S0590', '067S0038', '099S0111', '114S0228', '109S1192',
       '072S1211', '052S1054', '109S0876', '062S0730', '036S0976',
       '010S0829', '052S0952', '052S0989', '137S0631', '126S0891',
       '011S1282', '014S1095', '137S0825', '021S0332', '014S0658',
       '013S0699', '007S0101', '053S0507', '099S0880', '067S0019',
       '033S0725', '057S1265', '035S0204', '031S0830'], dtype='<U8')

In [ ]:
df_bl.head()

    RID        PTID VISCODE  ...   FAQ       PHS     label
0     2  011_S_0002      bl  ...   0.0 -0.096111  011S0002
16    3  011_S_0003      bl  ...  10.0  0.414711  011S0003
21    4  022_S_0004      bl  ...   0.0  0.647089  022S0004
27    5  011_S_0005      bl  ...   0.0 -0.373703  011S0005
34    6  100_S_0006      bl  ...   0.0 -0.105310  100S0006

[5 rows x 21 columns]

In [ ]:
df_bl['label'] = df_bl['label'].astype('category')
sorter = labels.tolist()
df_bl['label'].cat.set_categories(sorter, inplace=True)

df_bl = df_bl.sort_values('label')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_bl.head()

       RID        PTID VISCODE  ...  FAQ       PHS     label
5769  1242  128_S_1242      bl  ...  0.0  0.568892  128S1242
1476   272  128_S_0272      bl  ...  0.0  0.358680  128S0272
5468  1155  002_S_1155      bl  ...  1.0 -0.009396  002S1155
2459   478  068_S_0478      bl  ...  1.0 -0.267112  068S0478
1882   351  031_S_0351      bl  ...  4.0 -0.194300  031S0351

[5 rows x 21 columns]

In [ ]:
df_bl.to_csv('/content/drive/My Drive/ADNI/Clinical2.csv', index=False)